name: Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

env:
  CI: true
  FORCE_COLOR: true
  TARGET_PLATFORM: WebGL

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Restore Library cache
        uses: actions/cache@v3
        with:
          path: src/Library
          key: Library-${{ env.TARGET_PLATFORM }}

      - uses: game-ci/unity-test-runner@v2.1.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: src
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: all

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Restore Library cache
        uses: actions/cache@v3
        with:
          path: src/Library
          key: Library-${{ env.TARGET_PLATFORM }}

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: src
          targetPlatform: ${{ env.TARGET_PLATFORM }}

      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ env.TARGET_PLATFORM }}
          path: build/${{ env.TARGET_PLATFORM }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.vercel.outputs.preview-url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Build-${{ env.TARGET_PLATFORM }}
          path: build

      - uses: amondnet/vercel-action@v25
        id: vercel
        with:
          github-comment: false
          vercel-args: '-b BUILD=${{ github.event.number }} -b BUILD_BRANCH=${{ github.head_ref }} -b ENVIRONMENT=preview'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: build/${{ env.TARGET_PLATFORM }}

      - name: Discord notification
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: '${{ vars.ITCH_GAME }} preview ${{ github.event.number }}/${{github.run_number}} is ready: ${{ steps.vercel.outputs.preview-url }}'
