name: Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

env:
  CI: true
  FORCE_COLOR: true
  TARGET_PLATFORM: WebGL

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Restore Library cache
        uses: actions/cache@v3
        with:
          path: src/Library
          key: Library-${{ env.TARGET_PLATFORM }}

      - uses: game-ci/unity-test-runner@v2.1.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: src
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: all
